### ISSUE TITLE
Test on other platforms than Raspbian

### ISSUE THREAD

**Issue by koenvervloesem** [koenvervloesem/snips-app-say-it-again#12]
Currently this app is only tested on Raspbian.

It would be helpful if someone could test the app on other platforms supported by Snips, such as other Linux distributions (especially Ubuntu), macOS and other ARM systems than the Raspberry Pi. I'd love to hear the result, positive or negative.

**Comment by Ultchad** [comment]
Tested on debian 9 x86 (on lxc container) 
All is OK

**Comment by koenvervloesem** [comment]
> Tested on debian 9 x86 (on lxc container)

Great, thanks for the confirmation, @Ultchad!
