### ISSUE TITLE
New feature: Repeat last task

### ISSUE THREAD

**Issue by philipp2310** [koenvervloesem/snips-app-say-it-again#2]
From Discord:
>eto today at 23:07 Uhr
another question: is it possible to restart the last action? "repeat" "again"
exmple : "Please give me more light in the living room"       and  "again"   it's possible ?

I think it is a good idea and would be willing to implement it in the next few weeks. (currently busy with another project)

Basic concept:
Listen to hermes/intent/#
if it is not the "repeat" skill:
Save the topic and message
if it is the "repeat" skill:
Republish the saved topic with the same message
(Possible problem: The Dialog-ID will be reused!)

Additional Idea:
Don't allow "old" skills to be repeated:
Forget the stored data after a configurable amount of time (Probably via threads so it is really gone)
This could be used for the other skills as well (You don't want your wife to ask Snips what your last sentence was when you are gone ;))

**Comment by koenvervloesem** [comment]
Yes that's a very natural question and I agree it would fit perfectly in this app. I actually had the same idea a few weeks ago and I even tried to implement it, but the republished intent didn't activate its action. I haven't found the time yet to delve into the issue, but I suspected the duplicate session ID to be the culprit indeed. It would be great if you could have a look at it.

Your additional idea is a great one too. I opened a new issue for it:  #3.

**Comment by koenvervloesem** [comment]
I now read your comment on Discord about the timeout feature:

> only thing i want to include that i don't know how: I want the app to forget the last command after ~1 minute and I don't mean just don't respond after that time, but really delete the information

After which Psycho answered [threading.Timer](https://docs.python.org/2/library/threading.html#timer-objects).

I include this for reference here.

**Comment by koenvervloesem** [comment]
Merged in #6
