### ISSUE TITLE
New feature: only repeat last sentence of the user who is asking

### ISSUE THREAD

**Issue by koenvervloesem** [koenvervloesem/snips-app-say-it-again#4]
I got this idea from #3 which was suggested by @philipp2310:

You want to prevent that your wife/kids/... can ask Snips what your last sentence was. This can be solved by implementing some sort of user management/detection: the app could then repeat the last sentence of the user asking for it, just like it's now repeating the last sentence on the site ID the user is using.

This could be implemented in the app by referring to custom hotwords for each user, but I don't have any experience yet with it. When I find some time to try out custom hotwords in Snips, I will definitely implement this feature.

**Comment by philipp2310** [comment]
The wakeword is only included in: hermes/hotword/default/detected
`{"siteId":"test","modelId":"hey_snips","modelVersion":"hey_snips_3.1_2018-04-13T15:27:35_model_0019","modelType":"universal","currentSensitivity":0.5}`

we would have to save that modelId in a temporary variable and wait for the hermes/asr/stopListening with the corresponding sessionId
`{"siteId":"test","sessionId":"762a3a6c-4143-4204-bd30-7c91e5b4988f"}`
This would be the shortest possible time to prevent two "simultaneous" wake words in different rooms to mess up each other.

If we wait longer (for the intent/say/tts that we want to save) the chance gets bigger, that another wake word overwrites the variable and we save it as the wrong person.

just some thoughts ^^

**Comment by koenvervloesem** [comment]
I'm closing this as the app won't be developed further.
